const countries: { country: string, code: string }[] = [
    {"country": "Afghanistan", "code": "AF"},
    {"country": "Îles Åland", "code": "AX"},
    {"country": "Albanie", "code": "AL"},
    {"country": "Algérie", "code": "DZ"},
    {"country": "Samoa américaines", "code": "AS"},
    {"country": "Andorre", "code": "AD"},
    {"country": "Angola", "code": "AO"},
    {"country": "Anguilla", "code": "AI"},
    {"country": "Antarctique", "code": "AQ"},
    {"country": "Antigua-et-Barbuda", "code": "AG"},
    {"country": "Argentine", "code": "AR"},
    {"country": "Arménie", "code": "AM"},
    {"country": "Aruba", "code": "AW"},
    {"country": "Australie", "code": "AU"},
    {"country": "Autriche", "code": "AT"},
    {"country": "Azerbaïdjan", "code": "AZ"},
    {"country": "Bahamas", "code": "BS"},
    {"country": "Bahreïn", "code": "BH"},
    {"country": "Bangladesh", "code": "BD"},
    {"country": "Barbade", "code": "BB"},
    {"country": "Biélorussie", "code": "BY"},
    {"country": "Belgique", "code": "BE"},
    {"country": "Belize", "code": "BZ"},
    {"country": "Bénin", "code": "BJ"},
    {"country": "Bermudes", "code": "BM"},
    {"country": "Bhoutan", "code": "BT"},
    {"country": "Bolivie", "code": "BO"},
    {"country": "Bosnie-Herzégovine", "code": "BA"},
    {"country": "Botswana", "code": "BW"},
    {"country": "Île Bouvet", "code": "BV"},
    {"country": "Brésil", "code": "BR"},
    {"country": "British Virgin Islands", "code": "VG"},
    {"country": "Territoire britannique de l’Océan Indien", "code": "IO"},
    {"country": "Brunei Darussalam", "code": "BN"},
    {"country": "Bulgarie", "code": "BG"},
    {"country": "Burkina Faso", "code": "BF"},
    {"country": "Burundi", "code": "BI"},
    {"country": "Cambodge", "code": "KH"},
    {"country": "Cameroun", "code": "CM"},
    {"country": "Canada", "code": "CA"},
    {"country": "Cap-Vert", "code": "CV"},
    {"country": "Iles Cayman", "code": "KY"},
    {"country": "République centrafricaine", "code": "CF"},
    {"country": "Tchad", "code": "TD"},
    {"country": "Chili", "code": "CL"},
    {"country": "Chine", "code": "CN"},
    {"country": "Hong Kong", "code": "HK"},
    {"country": "Macao", "code": "MO"},
    {"country": "Île Christmas", "code": "CX"},
    {"country": "Îles Cocos", "code": "CC"},
    {"country": "Colombie", "code": "CO"},
    {"country": "Comores", "code": "KM"},
    {"country": "République du Congo", "code": "CG"},
    {"country": "République démocratique du Congo", "code": "CD"},
    {"country": "Îles Cook", "code": "CK"},
    {"country": "Costa Rica", "code": "CR"},
    {"country": "Côte d’Ivoire", "code": "CI"},
    {"country": "Croatie", "code": "HR"},
    {"country": "Cuba", "code": "CU"},
    {"country": "Chypre", "code": "CY"},
    {"country": "République tchèque", "code": "CZ"},
    {"country": "Danemark", "code": "DK"},
    {"country": "Djibouti", "code": "DJ"},
    {"country": "Dominique", "code": "DM"},
    {"country": "République dominicaine", "code": "DO"},
    {"country": "Équateur", "code": "EC"},
    {"country": "Égypte", "code": "EG"},
    {"country": "Salvador", "code": "SV"},
    {"country": "Guinée équatoriale", "code": "GQ"},
    {"country": "Érythrée", "code": "ER"},
    {"country": "Estonie", "code": "EE"},
    {"country": "Éthiopie", "code": "ET"},
    {"country": "Îles Falkland", "code": "FK"},
    {"country": "Îles Féroé", "code": "FO"},
    {"country": "Fidji", "code": "FJ"},
    {"country": "Finlande", "code": "FI"},
    {"country": "France", "code": "FR"},
    {"country": "Guyane française", "code": "GF"},
    {"country": "Polynésie française", "code": "PF"},
    {"country": "Terres australes et antarctiques françaises", "code": "TF"},
    {"country": "Gabon", "code": "GA"},
    {"country": "Gambie", "code": "GM"},
    {"country": "Géorgie", "code": "GE"},
    {"country": "Allemagne", "code": "DE"},
    {"country": "Ghana", "code": "GH"},
    {"country": "Gibraltar", "code": "GI"},
    {"country": "Grèce", "code": "GR"},
    {"country": "Groenland", "code": "GL"},
    {"country": "Grenade", "code": "GD"},
    {"country": "Guadeloupe", "code": "GP"},
    {"country": "Guam", "code": "GU"},
    {"country": "Guatemala", "code": "GT"},
    {"country": "Guernesey", "code": "GG"},
    {"country": "Guinée", "code": "GN"},
    {"country": "Guinée-Bissau", "code": "GW"},
    {"country": "Guyane", "code": "GY"},
    {"country": "Haïti", "code": "HT"},
    {"country": "Îles Heard-et-MacDonald", "code": "HM"},
    {"country": "Saint-Siège (Vatican)", "code": "VA"},
    {"country": "Honduras", "code": "HN"},
    {"country": "Hongrie", "code": "HU"},
    {"country": "Islande", "code": "IS"},
    {"country": "Inde", "code": "IN"},
    {"country": "Indonésie", "code": "ID"},
    {"country": "Iran", "code": "IR"},
    {"country": "Irak", "code": "IQ"},
    {"country": "Irlande", "code": "IE"},
    {"country": "Ile de Man", "code": "IM"},
    {"country": "Israël", "code": "IL"},
    {"country": "Italie", "code": "IT"},
    {"country": "Jamaïque", "code": "JM"},
    {"country": "Japon", "code": "JP"},
    {"country": "Jersey", "code": "JE"},
    {"country": "Jordanie", "code": "JO"},
    {"country": "Kazakhstan", "code": "KZ"},
    {"country": "Kenya", "code": "KE"},
    {"country": "Kiribati", "code": "KI"},
    {"country": "Corée du Nord", "code": "KP"},
    {"country": "Corée du Sud", "code": "KR"},
    {"country": "Koweït", "code": "KW"},
    {"country": "Kirghizistan", "code": "KG"},
    {"country": "Laos", "code": "LA"},
    {"country": "Lettonie", "code": "LV"},
    {"country": "Liban", "code": "LB"},
    {"country": "Lesotho", "code": "LS"},
    {"country": "Libéria", "code": "LR"},
    {"country": "Libye", "code": "LY"},
    {"country": "Liechtenstein", "code": "LI"},
    {"country": "Lituanie", "code": "LT"},
    {"country": "Luxembourg", "code": "LU"},
    {"country": "Macédoine", "code": "MK"},
    {"country": "Madagascar", "code": "MG"},
    {"country": "Malawi", "code": "MW"},
    {"country": "Malaisie", "code": "MY"},
    {"country": "Maldives", "code": "MV"},
    {"country": "Mali", "code": "ML"},
    {"country": "Malte", "code": "MT"},
    {"country": "Îles Marshall", "code": "MH"},
    {"country": "Martinique", "code": "MQ"},
    {"country": "Mauritanie", "code": "MR"},
    {"country": "Maurice", "code": "MU"},
    {"country": "Mayotte", "code": "YT"},
    {"country": "Mexique", "code": "MX"},
    {"country": "Micronésie", "code": "FM"},
    {"country": "Moldavie", "code": "MD"},
    {"country": "Monaco", "code": "MC"},
    {"country": "Mongolie", "code": "MN"},
    {"country": "Monténégro", "code": "ME"},
    {"country": "Montserrat", "code": "MS"},
    {"country": "Maroc", "code": "MA"},
    {"country": "Mozambique", "code": "MZ"},
    {"country": "Myanmar", "code": "MM"},
    {"country": "Namibie", "code": "NA"},
    {"country": "Nauru", "code": "NR"},
    {"country": "Népal", "code": "NP"},
    {"country": "Pays-Bas", "code": "NL"},
    {"country": "Nouvelle-Calédonie", "code": "NC"},
    {"country": "Nouvelle-Zélande", "code": "NZ"},
    {"country": "Nicaragua", "code": "NI"},
    {"country": "Niger", "code": "NE"},
    {"country": "Nigeria", "code": "NG"},
    {"country": "Niue", "code": "NU"},
    {"country": "Île Norfolk", "code": "NF"},
    {"country": "Îles Mariannes du Nord", "code": "MP"},
    {"country": "Norvège", "code": "NO"},
    {"country": "Oman", "code": "OM"},
    {"country": "Pakistan", "code": "PK"},
    {"country": "Palau", "code": "PW"},
    {"country": "Palestine", "code": "PS"},
    {"country": "Panama", "code": "PA"},
    {"country": "Papouasie-Nouvelle-Guinée", "code": "PG"},
    {"country": "Paraguay", "code": "PY"},
    {"country": "Pérou", "code": "PE"},
    {"country": "Philippines", "code": "PH"},
    {"country": "Pitcairn", "code": "PN"},
    {"country": "Pologne", "code": "PL"},
    {"country": "Portugal", "code": "PT"},
    {"country": "Puerto Rico", "code": "PR"},
    {"country": "Qatar", "code": "QA"},
    {"country": "Réunion", "code": "RE"},
    {"country": "Roumanie", "code": "RO"},
    {"country": "Russie", "code": "RU"},
    {"country": "Rwanda", "code": "RW"},
    {"country": "Saint-Barthélemy", "code": "BL"},
    {"country": "Sainte-Hélène", "code": "SH"},
    {"country": "Saint-Kitts-et-Nevis", "code": "KN"},
    {"country": "Sainte-Lucie", "code": "LC"},
    {"country": "Saint-Martin (partie française)", "code": "MF"},
    {"country": "Saint-Martin (partie néerlandaise)", "code": "SX"},
    {"country": "Saint-Pierre-et-Miquelon", "code": "PM"},
    {"country": "Saint-Vincent-et-les Grenadines", "code": "VC"},
    {"country": "Samoa", "code": "WS"},
    {"country": "Saint-Marin", "code": "SM"},
    {"country": "Sao Tomé-et-Principe", "code": "ST"},
    {"country": "Arabie Saoudite", "code": "SA"},
    {"country": "Sénégal", "code": "SN"},
    {"country": "Serbie", "code": "RS"},
    {"country": "Seychelles", "code": "SC"},
    {"country": "Sierra Leone", "code": "SL"},
    {"country": "Singapour", "code": "SG"},
    {"country": "Slovaquie", "code": "SK"},
    {"country": "Slovénie", "code": "SI"},
    {"country": "Îles Salomon", "code": "SB"},
    {"country": "Somalie", "code": "SO"},
    {"country": "Afrique du Sud", "code": "ZA"},
    {"country": "Géorgie du Sud et les îles Sandwich du Sud", "code": "GS"},
    {"country": "Sud-Soudan", "code": "SS"},
    {"country": "Espagne", "code": "ES"},
    {"country": "Sri Lanka", "code": "LK"},
    {"country": "Soudan", "code": "SD"},
    {"country": "Suriname", "code": "SR"},
    {"country": "Svalbard et Jan Mayen", "code": "SJ"},
    {"country": "Eswatini", "code": "SZ"},
    {"country": "Suède", "code": "SE"},
    {"country": "Suisse", "code": "CH"},
    {"country": "Syrie", "code": "SY"},
    {"country": "Taiwan", "code": "TW"},
    {"country": "Tadjikistan", "code": "TJ"},
    {"country": "Tanzanie", "code": "TZ"},
    {"country": "Thaïlande", "code": "TH"},
    {"country": "Timor-Leste", "code": "TL"},
    {"country": "Togo", "code": "TG"},
    {"country": "Tokelau", "code": "TK"},
    {"country": "Tonga", "code": "TO"},
    {"country": "Trinité-et-Tobago", "code": "TT"},
    {"country": "Tunisie", "code": "TN"},
    {"country": "Turquie", "code": "TR"},
    {"country": "Turkménistan", "code": "TM"},
    {"country": "Îles Turques-et-Caïques", "code": "TC"},
    {"country": "Tuvalu", "code": "TV"},
    {"country": "Ouganda", "code": "UG"},
    {"country": "Ukraine", "code": "UA"},
    {"country": "Émirats Arabes Unis", "code": "AE"},
    {"country": "Royaume-Uni", "code": "GB"},
    {"country": "États-Unis", "code": "US"},
    {"country": "Îles mineures éloignées des États-Unis", "code": "UM"},
    {"country": "Uruguay", "code": "UY"},
    {"country": "Ouzbékistan", "code": "UZ"},
    {"country": "Vanuatu", "code": "VU"},
    {"country": "Venezuela", "code": "VE"},
    {"country": "Viêt Nam", "code": "VN"},
    {"country": "Îles Vierges américaines", "code": "VI"},
    {"country": "Wallis-et-Futuna", "code": "WF"},
    {"country": "Sahara occidental", "code": "EH"},
    {"country": "Yémen", "code": "YE"},
    {"country": "Zambie", "code": "ZM"},
    {"country": "Zimbabwe", "code": "ZW"},
];

export const getCountry = (code: string): { country: string, code: string } | undefined => {
    return countries.find(c => c.code === code);
}